server:
  port: 9008
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitydb?serverTimezone=Asia/Seoul
    username: test
    password: test1234
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true